<a href="https://colab.research.google.com/github/SagarSitaula1/Data-Visual/blob/main/SQL_Joins.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SQL Joins

In [2]:
from google.colab import auth
auth.authenticate_user()
print('Authenticated')

Authenticated

In [3]:
%%bigquery --project deep-presence-338719
SELECT *
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips`
LIMIT 10

      trip_id  ... duration_minutes
0  9900289692  ...               39
1  9900285987  ...               31
2  9900285989  ...               31
3  9900285991  ...               30
4  9900286140  ...               19
5  9900286143  ...               17
6  9900286171  ...                6
7  9900286214  ...                0
8  9900286540  ...               12
9    13575843  ...               47

[10 rows x 9 columns]

In [4]:
%%bigquery --project deep-presence-338719

SELECT *
FROM `bigquery-public-data.austin_bikeshare.bikeshare_stations`
limit 5

   station_id  ...             modified_date
0        2576  ... 2021-01-04 12:00:00+00:00
1        2712  ... 2021-01-04 12:00:00+00:00
2        3381  ... 2021-01-04 12:00:00+00:00
3        3464  ... 2021-01-04 12:00:00+00:00
4        1001  ... 2021-01-04 12:00:00+00:00

[5 rows x 14 columns]

In [9]:
%%bigquery --project deep-presence-338719

SELECT *
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips`
where start_station_name = 'parkland'
limit 5

Empty DataFrame
Columns: [trip_id, subscriber_type, bikeid, start_time, start_station_id, start_station_name, end_station_id, end_station_name, duration_minutes]
Index: []

In [6]:
%%bigquery --project deep-presence-338719

SELECT *
FROM `bigquery-public-data.austin_bikeshare.bikeshare_stations`
where property_type = 'sidewalk'
limit 5

   station_id  ...             modified_date
0        1111  ... 2021-11-04 02:12:00+00:00
1          11  ... 2021-11-04 02:24:00+00:00
2        4699  ... 2021-07-27 08:25:00+00:00
3        2570  ... 2021-01-04 12:00:00+00:00
4        2496  ... 2021-01-04 12:00:00+00:00

[5 rows x 14 columns]

In [7]:
%%bigquery --project deep-presence-338719
WITH t as(
SELECT *
FROM `bigquery-public-data.austin_bikeshare.bikeshare_stations`
WHERE property_type = 'sidewalk')

SELECT *
FROM t as table1 JOIN `bigquery-public-data.austin_bikeshare.bikeshare_trips` as table2 ON table1.name = table2.start_station_name
LIMIT 5

   station_id  ... duration_minutes
0        3291  ...               20
1        3291  ...               35
2        3291  ...               19
3        3291  ...                7
4        3294  ...               17

[5 rows x 23 columns]

In [26]:
%%bigquery --project deep-presence-338719
SELECT type.station_id,type.name, type.property_type,trips.start_station_name
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips` as trips LEFT OUTER JOIN `bigquery-public-data.austin_bikeshare.bikeshare_stations` as type
          on trips.start_station_name = type.name
LIMIT 50

    station_id  ...                       start_station_name
0         1006  ...                         Zilker Park West
1         2712  ...                  Toomey Rd @ South Lamar
2         2712  ...                  Toomey Rd @ South Lamar
3         2712  ...                  Toomey Rd @ South Lamar
4         2541  ...          State Capitol @ 14th & Colorado
5         2541  ...          State Capitol @ 14th & Colorado
6         2536  ...                         Waller & 6th St.
7         2712  ...                  Toomey Rd @ South Lamar
8         2536  ...                         Waller & 6th St.
9         3464  ...                               Pease Park
10        2541  ...          State Capitol @ 14th & Colorado
11        2541  ...          State Capitol @ 14th & Colorado
12        2541  ...          State Capitol @ 14th & Colorado
13        2712  ...                  Toomey Rd @ South Lamar
14        2536  ...                         Waller & 6th St.
15        2536  ...                         Waller & 6th St.
16        2712  ...                  Toomey Rd @ South Lamar
17        2823  ...  Capital Metro HQ - East 5th at Broadway
18        1006  ...                         Zilker Park West
19        2823  ...  Capital Metro HQ - East 5th at Broadway
20        2536  ...                         Waller & 6th St.
21        2536  ...                         Waller & 6th St.
22        2536  ...                         Waller & 6th St.
23        2536  ...                         Waller & 6th St.
24        2712  ...                  Toomey Rd @ South Lamar
25        2823  ...  Capital Metro HQ - East 5th at Broadway
26        2823  ...  Capital Metro HQ - East 5th at Broadway
27        2536  ...                         Waller & 6th St.
28        2541  ...          State Capitol @ 14th & Colorado
29        2536  ...                         Waller & 6th St.
30        2568  ...           East 11th St. at Victory Grill
31        2568  ...           East 11th St. at Victory Grill
32        3291  ...                       11th & San Jacinto
33        2536  ...                         Waller & 6th St.
34        3291  ...                       11th & San Jacinto
35        3291  ...                       11th & San Jacinto
36        2568  ...           East 11th St. at Victory Grill
37        1008  ...                             Nueces @ 3rd
38        1008  ...                             Nueces @ 3rd
39        3291  ...                       11th & San Jacinto
40        1008  ...                             Nueces @ 3rd
41        1008  ...                             Nueces @ 3rd
42        1008  ...                             Nueces @ 3rd
43        2536  ...                         Waller & 6th St.
44        2823  ...  Capital Metro HQ - East 5th at Broadway
45        3293  ...                    East 2nd & Pedernales
46        2568  ...           East 11th St. at Victory Grill
47        1008  ...                             Nueces @ 3rd
48        2546  ...                 ACC - West & 12th Street
49        1008  ...                             Nueces @ 3rd

[50 rows x 4 columns]