<a href="https://colab.research.google.com/github/SagarSitaula1/Data-Visual/blob/main/SQL_Joins.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SQL Joins

In [ ]:
from google.colab import auth
auth.authenticate_user()
print('Authenticated')

Authenticated

In [4]:
%%bigquery --project deep-presence-338719
SELECT *
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips`
LIMIT 10

      trip_id  ... duration_minutes
0  9900289692  ...               39
1  9900285987  ...               31
2  9900285989  ...               31
3  9900285991  ...               30
4  9900286140  ...               19
5  9900286143  ...               17
6  9900286171  ...                6
7  9900286214  ...                0
8  9900286540  ...               12
9    13575843  ...               47

[10 rows x 9 columns]

In [9]:
%%bigquery --project deep-presence-338719

SELECT *
FROM `bigquery-public-data.austin_bikeshare.bikeshare_stations`
limit 5

   station_id  ...             modified_date
0        2576  ... 2021-01-04 12:00:00+00:00
1        2712  ... 2021-01-04 12:00:00+00:00
2        3381  ... 2021-01-04 12:00:00+00:00
3        3464  ... 2021-01-04 12:00:00+00:00
4        1001  ... 2021-01-04 12:00:00+00:00

[5 rows x 14 columns]

In [22]:
%%bigquery --project deep-presence-338719

SELECT *
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips`
where start_ = 'parkland'
limit 5

   station_id  ...             modified_date
0        3687  ... 2021-01-04 12:00:00+00:00
1        3684  ... 2021-01-04 12:00:00+00:00
2        2572  ... 2021-01-04 12:00:00+00:00
3        2575  ... 2021-01-04 12:00:00+00:00
4        2574  ... 2021-01-04 12:00:00+00:00

[5 rows x 14 columns]

In [23]:
%%bigquery --project deep-presence-338719

SELECT *
FROM `bigquery-public-data.austin_bikeshare.bikeshare_stations`
where property_type = 'sidewalk'
limit 5

   station_id  ...             modified_date
0        1111  ... 2021-11-04 02:12:00+00:00
1          11  ... 2021-11-04 02:24:00+00:00
2        4699  ... 2021-07-27 08:25:00+00:00
3        2570  ... 2021-01-04 12:00:00+00:00
4        2496  ... 2021-01-04 12:00:00+00:00

[5 rows x 14 columns]

In [33]:
%%bigquery --project deep-presence-338719
WITH t as(
SELECT *
FROM `bigquery-public-data.austin_bikeshare.bikeshare_stations`
WHERE property_type = 'sidewalk')

SELECT *
FROM t as table1 JOIN `bigquery-public-data.austin_bikeshare.bikeshare_trips` as table2 ON table1.name = table2.start_station_name
LIMIT 5

   station_id  ... duration_minutes
0        3291  ...               20
1        3291  ...               35
2        3291  ...               19
3        3291  ...                7
4        3294  ...               17

[5 rows x 23 columns]

In [ ]:
%%bigquery --project deep-presence-338719
SELECT